version: '3.8'

networks:
    postgres_default:
        ipam:
            driver: default
            config:
                 - subnet: 192.168.0.0/24
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - ./bd:/var/lib/postgresql/data
      - ./demo:/demo
    ports:
      - 5432:5432
    networks:
      postgres_default: 
        ipv4_address: 192.168.0.4
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 80:80
    networks:
      postgres_default: 
        ipv4_address: 192.168.0.5